# Generated by Django 3.1.3 on 2020-11-18 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TaskModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('memo', models.TextField()),
                ('priority', models.CharField(choices=[('danger', 'High'), ('info', 'Normal'), ('success', 'Low')], max_length=50)),
                ('deadline', models.DateField()),
            ],
        ),
    ]
